ChartValues:
  postgresql:
    enabled: true
    primary:
      persistence:
        storageClass: alicloud-disk-essd
        size: 40Gi
        enabled: true
  service:
    type: LoadBalancer
  persistence:
    persistentVolumeClaim:
      registry:
        storageClass: alicloud-disk-essd
        size: 40Gi
      jobservice:
        storageClass: alicloud-disk-essd
        size: 40Gi
      trivy:
        storageClass: alicloud-disk-essd
        size: 40Gi
    enabled: true
  redis:
    enabled: true
    master:
      persistence:
        storageClass: alicloud-disk-essd
        size: 40Gi
        enabled: true
  adminPassword: root@12345
HelmChartPath: .
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: yehanyh/harbor-helm
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: yehanyh
Branch: main
Platform: github
